export const theads = [
    { label: "Student ID" },
  { label: "Lao Name" },
  { label: "English Firstname" },
  { label: "English Lastname" },
  { label: "Nickname" },
  { label: "Date of Birth" },
  { label: "Gender" },
  { label: "Permanent Address" },
  { label: "University - Lao Name" },
  { label: "University - Vietnamese Name" },
//   { label: "University - English Name" },
//   { label: "University - Shortcut" },
  { label: "Major - Lao Major" },
  { label: "Major - Vietnamese Major" },
  { label: "Degree - Lao Degree" },
  { label: "Degree - Vietnamese Degree" },
  { label: "Scholarship - Type" },
  { label: "Scholarship - Lao" },
  { label: "Scholarship - Vietnamese" },
  { label: "Scholarship - University" },
  { label: "Duration - From" },
  { label: "Duration - To" },
  { label: "Phone - Phone Number" },
  { label: "Phone - Emergency Contact" },
  { label: "Phone - Relationship" },
  { label: "Facebook URL" },
  { label: "Visa - From" },
  { label: "Visa - To" },
  { label: "Passport - Passport Number" },
  { label: "Passport - Expiry Date" },
  { label: "Residence Address" },
];
